filebeat.config:
  modules:
    path: ./modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - '/var/log/filebeat/app.log'
  exclude_lines: ['^ERR']

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOSTS:10.1.19.1:9204}"]
  worker: 1
  compression_level: 3
  escape_html: false
  loadbalance: false
  ssl.enabled: false
