version: '3.8'

services:
  filebeat:
    image: beats/filebeat:${VERSION}
    container_name: ${SERVICE_NAME}-filebeat
    hostname: filebeat
    restart: unless-stopped
    env_file: .env
    environment:
      - LOGSTASH_HOSTS=${LOGSTASH_HOSTS}
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/var/log/filebeat:ro

  logstash:
    image: logstash/logstash:${VERSION}
    container_name: ${SERVICE_NAME}-logstash
    hostname: logstash
    restart: unless-stopped
    env_file: .env
    environment:
      - ELASTICHOST=${ELASTICHOST}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/settings:/usr/share/logstash/config
      